---
title: "Plotting with Plotly"
author: "Omar Ali Fdal"
date: "27 October 2017"
output: slidy_presentation
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(ggplot2)
library(plotly)
```

## Plotting with Plotly

This is a presentation showing multivariate plot based on `mtcars` dataset (builtin in R).

Part of Week 3 assignment of the Developing Data Products course.

## Miles p. Galon vs. Quarter Mile time

```{r qsec, echo=FALSE}
data(mtcars)
mtcars$am <- factor(mtcars$am, levels = c(0, 1),
                    labels = c("automatic", "manual"))
# str(mtcars)

plt <- ggplot(data=mtcars, mapping=aes(y=mpg, x=qsec, shape=am, size=wt, color=hp)) +
  geom_point(alpha=0.5) +
  geom_smooth(method="lm") + 
  scale_color_gradient(low="lightBlue", high="darkBlue")

ggplotly(plt)
```

## The code
```{r qsecCode, echo=TRUE, eval=FALSE}
data(mtcars)
mtcars$am <- factor(mtcars$am, levels = c(0, 1),
                    labels = c("automatic", "manual"))
str(mtcars)

plt <- ggplot(data=mtcars, mapping=aes(y=mpg, x=qsec, shape=am, size=wt, color=hp)) +
  geom_point(alpha=0.5) +
  geom_smooth(method="lm") + 
  scale_color_gradient(low="lightBlue", high="darkBlue")

ggplotly(plt)
```


